- import_playbook: /opt/software/sinq-amorsim/ansible/amor.yml

- hosts: simulation
  tasks:
    - name: change the generator config file
      become: yes
      copy:
        src: generator.config.json
        dest: /opt/amor/simfiles/config.json
        force: yes
